spring:
  dataSource:
    username: root
    password: m123
    url: jdbc:mysql://mysql:3306/tools?useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

